name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: robarros/workflows/.github/workflows/build.yaml@main
    secrets: inherit

  deploy:
    uses: robarros/workflows/.github/workflows/deploy.yaml@main
    needs: build
    secrets: inherit
    with:
      image-tag: ${{ needs.build.outputs.image-tag}}

      